// @ts-nocheck — types generated by `npx convex dev`
import { query } from "./_generated/server";
import { v } from "convex/values";

export const listByDestination = query({
  args: {
    destinationSlug: v.string(),
    difficulty: v.optional(
      v.union(v.literal("beginner"), v.literal("intermediate"), v.literal("expert"))
    ),
    budgetMax: v.optional(v.number()),
    durationDays: v.optional(v.number()),
  },
  handler: async (ctx, args) => {
    const destination = await ctx.db
      .query("destinations")
      .withIndex("by_slug", (q) => q.eq("slug", args.destinationSlug))
      .unique();

    if (!destination) return [];

    let agencies = await ctx.db
      .query("agencies")
      .withIndex("by_destination", (q) => q.eq("destinationId", destination._id))
      .filter((q) => q.eq(q.field("isActive"), true))
      .collect();

    if (args.difficulty) {
      const treks = await ctx.db
        .query("treks")
        .withIndex("by_difficulty", (q) => q.eq("difficulty", args.difficulty!))
        .filter((q) => q.eq(q.field("destinationId"), destination._id))
        .collect();

      const agencyIdsWithDifficulty = new Set(treks.map((t) => t.agencyId));
      agencies = agencies.filter((a) => agencyIdsWithDifficulty.has(a._id));
    }

    if (args.budgetMax) {
      const treks = await ctx.db
        .query("treks")
        .withIndex("by_destination", (q) => q.eq("destinationId", destination._id))
        .filter((q) => q.lte(q.field("pricePerPerson"), args.budgetMax!))
        .collect();

      const agencyIdsInBudget = new Set(treks.map((t) => t.agencyId));
      agencies = agencies.filter((a) => agencyIdsInBudget.has(a._id));
    }

    return agencies;
  },
});

export const getById = query({
  args: { id: v.id("agencies") },
  handler: async (ctx, args) => {
    return await ctx.db.get(args.id);
  },
});
