// @ts-nocheck — types generated by `npx convex dev`
// eslint-disable-next-line @typescript-eslint/no-require-imports
import { query } from "./_generated/server";
import { v } from "convex/values";

export const listDestinations = query({
  args: {},
  // eslint-disable-next-line @typescript-eslint/no-explicit-any
  handler: async (ctx: any) => {
    return await ctx.db
      .query("destinations")
      .filter((q: any) => q.eq(q.field("isActive"), true))
      .collect();
  },
});

export const getBySlug = query({
  args: { slug: v.string() },
  // eslint-disable-next-line @typescript-eslint/no-explicit-any
  handler: async (ctx: any, args: any) => {
    return await ctx.db
      .query("destinations")
      .withIndex("by_slug", (q: any) => q.eq("slug", args.slug))
      .unique();
  },
});
