// @ts-nocheck — types generated by `npx convex dev`
import { query } from "./_generated/server";
import { v } from "convex/values";

export const listByDestination = query({
  args: { destinationSlug: v.string() },
  handler: async (ctx, args) => {
    const destination = await ctx.db
      .query("destinations")
      .withIndex("by_slug", (q) => q.eq("slug", args.destinationSlug))
      .unique();

    if (!destination) return [];

    return await ctx.db
      .query("guides")
      .withIndex("by_destination", (q) => q.eq("destinationId", destination._id))
      .filter((q) => q.eq(q.field("isActive"), true))
      .collect();
  },
});

export const getById = query({
  args: { id: v.id("guides") },
  handler: async (ctx, args) => {
    return await ctx.db.get(args.id);
  },
});
