// @ts-nocheck — types generated by `npx convex dev`
import { mutation } from "./_generated/server";
import { v } from "convex/values";

export const createInquiry = mutation({
  args: {
    trekId: v.optional(v.id("treks")),
    agencyId: v.optional(v.id("agencies")),
    guideId: v.optional(v.id("guides")),
    destinationId: v.id("destinations"),
    userName: v.string(),
    userPhone: v.string(),
    userEmail: v.string(),
    groupSize: v.number(),
    preferredStartDate: v.string(),
    preferredEndDate: v.optional(v.string()),
    budgetPerPerson: v.optional(v.number()),
    message: v.optional(v.string()),
    source: v.string(),
  },
  handler: async (ctx, args) => {
    return await ctx.db.insert("inquiries", {
      ...args,
      status: "new",
    });
  },
});
