// @ts-nocheck — types generated by `npx convex dev`
import { mutation } from "./_generated/server";

export const updateHeroImages = mutation({
  args: {},
  handler: async (ctx) => {
    const images: Record<string, string> = {
      mussoorie:
        "https://imgs.search.brave.com/OQ-8afLONlRGdJC-2kddtwm--_ImqHqTOhS-7ohVBC0/rs:fit:860:0:0:0/g:ce/aHR0cHM6Ly90My5m/dGNkbi5uZXQvanBn/LzAyLzMzLzIzLzc2/LzM2MF9GXzIzMzIz/NzY5N19IejZZMVl1/bVNKRnBQdVpiVzRl/SkxybFRpYm9JV1RE/ZC5qcGc",
      rishikesh:
        "https://imgs.search.brave.com/Y4znFaNUH6olmUWvZgmT27rouDCUUeLue0sgeUbcxcI/rs:fit:860:0:0:0/g:ce/aHR0cHM6Ly90My5m/dGNkbi5uZXQvanBn/LzE4LzAxLzIxLzM2/LzM2MF9GXzE4MDEy/MTM2MTdfNzZ2ejhW/QnlWbGZjeXNnNWpx/QW5iS08wV1djZmVD/SE8uanBn",
      chopta:
        "https://imgs.search.brave.com/ihB3ZwCfSSKeS8H8ksOfLQJ7UY7FbUWENrw3jXE8m8k/rs:fit:860:0:0:0/g:ce/aHR0cHM6Ly9tZWRp/YS5nZXR0eWltYWdl/cy5jb20vaWQvMTI1/MjkwMzIxMi9waG90/by9vbi10aGUtd2F5/LXRvLWNoYW5kcmFz/aGlsYS1zdW1taXQt/bmVhci10dW5nbmF0/aC1zaGl2YS10ZW1w/bGUtY2hvcHRhLXR1/bmduYXRoLWNoYW5k/cmFzaGlsYS5qcGc_/cz02MTJ4NjEyJnc9/MCZrPTIwJmM9OHlL/WHFNbE5xc2NXa05y/TFlZU2lENlBJamJl/LWxRRzJCVXA3LThK/ckRQND0",
      kedarkantha:
        "https://imgs.search.brave.com/vSiRVLqf2TMI3d8C8Apy-N3lnmKzwcIHKyL2M-u3TSo/rs:fit:860:0:0:0/g:ce/aHR0cHM6Ly9wcmV2/aWV3LnJlZGQuaXQv/YS1waWN0dXJlLWZy/b20tbXkta2VkYXJr/YW50aGEtdHJlay12/MC13MTZteGd0bmti/YWQxLmpwZWc_d2lk/dGg9NjQwJmNyb3A9/c21hcnQmYXV0bz13/ZWJwJnM9NjBkNGEz/ZWIzOWVhZDFmYTlk/NzE1YWJmMGJiMTBl/NDM5ODAxZTM3Mw",
      joshimath:
        "https://imgs.search.brave.com/EpD3jeIT9hmkJUMw9fVX61t2GI21DrnqaeD5DH0Kq0s/rs:fit:860:0:0:0/g:ce/aHR0cHM6Ly9oYmxp/bWcubW10Y2RuLmNv/bS9jb250ZW50L2h1/YmJsZS9pbWcvZGVz/dGltYWdlL21tdC9h/Y3Rpdml0aWVzL3Rf/dHJwL21fSm9zaGlt/YXRoX2Rlc3RpbmF0/aW9uX2xhbmRzY2Fw/ZV80X2xfNDM4Xzg1/Ni5qcGc_aW09UmVz/aXplPSg3NTAsMzk5/KQ",
    };

    let updated = 0;
    for (const [slug, heroImageUrl] of Object.entries(images)) {
      const dest = await ctx.db
        .query("destinations")
        .withIndex("by_slug", (q) => q.eq("slug", slug))
        .unique();
      if (dest) {
        await ctx.db.patch(dest._id, { heroImageUrl });
        updated++;
      }
    }
    return { message: "Hero images updated", updated };
  },
});

/** Derives trust score + breakdown from raw metrics */
function makeTrust(
  rating: number,
  reviews: number,
  years: number,
  verified: boolean
) {
  const r = Math.round(((rating - 3) / 2) * 40);
  const rv = Math.min(20, Math.floor(reviews / 25));
  const ya = Math.min(20, Math.floor(years / 2));
  const vs = verified ? 20 : 0;
  const rt = 12;
  return {
    trustScore: r + rv + ya + vs + rt,
    trustScoreBreakdown: {
      googleRating: r,
      reviewVolume: rv,
      yearsActive: ya,
      verifiedStatus: vs,
      responseTime: rt,
    },
  };
}

// ─── 1. DESTINATIONS ────────────────────────────────────────────────────────

export const seedDestinations = mutation({
  args: {},
  handler: async (ctx) => {
    const destinations = [
      {
        name: "Mussoorie",
        slug: "mussoorie",
        region: "Uttarakhand",
        heroImageUrl:
          "https://upload.wikimedia.org/wikipedia/commons/thumb/5/5c/Mussoorie_Queen_of_Hills.jpg/1280px-Mussoorie_Queen_of_Hills.jpg",
        description:
          "Known as the Queen of Hills, Mussoorie sits at 2,005m in the Garhwal Himalayan range. A favourite year-round hill station with scenic trails, waterfalls and colonial charm.",
        altitude: 2005,
        bestMonths: ["March", "April", "May", "September", "October", "November"],
        agencyCount: 0,
        startingPrice: 2500,
        isActive: true,
      },
      {
        name: "Rishikesh",
        slug: "rishikesh",
        region: "Uttarakhand",
        heroImageUrl:
          "https://upload.wikimedia.org/wikipedia/commons/thumb/3/3e/Laxman_Jhula_Rishikesh.jpg/1280px-Laxman_Jhula_Rishikesh.jpg",
        description:
          "The adventure capital of India on the banks of the Ganges. Gateway to the Garhwal Himalayas — white-water rafting, yoga, camping and multi-day treks all start here.",
        altitude: 372,
        bestMonths: ["February", "March", "April", "May", "September", "October", "November"],
        agencyCount: 0,
        startingPrice: 1800,
        isActive: true,
      },
      {
        name: "Chopta",
        slug: "chopta",
        region: "Uttarakhand",
        heroImageUrl:
          "https://upload.wikimedia.org/wikipedia/commons/thumb/6/6e/Tungnath_Temple.jpg/1280px-Tungnath_Temple.jpg",
        description:
          "Called the Mini Switzerland of India. At 2,680m, Chopta is the base for the Tungnath–Chandrashila trek — one of the most scenic winter treks in the Himalayas.",
        altitude: 2680,
        bestMonths: ["March", "April", "May", "October", "November", "December", "January"],
        agencyCount: 0,
        startingPrice: 3200,
        isActive: true,
      },
      {
        name: "Kedarkantha",
        slug: "kedarkantha",
        region: "Uttarakhand",
        heroImageUrl:
          "https://upload.wikimedia.org/wikipedia/commons/thumb/2/2d/Kedarkantha_peak.jpg/1280px-Kedarkantha_peak.jpg",
        description:
          "A perfect winter summit trek at 3,810m. Kedarkantha offers meadows blanketed in snow, dense pine forests and 360° panoramic views of peaks including Bandarpoonch and Swargarohini.",
        altitude: 3810,
        bestMonths: ["December", "January", "February", "March", "April"],
        agencyCount: 0,
        startingPrice: 4500,
        isActive: true,
      },
      {
        name: "Joshimath",
        slug: "joshimath",
        region: "Uttarakhand",
        heroImageUrl:
          "https://upload.wikimedia.org/wikipedia/commons/thumb/3/38/Valley_of_Flowers_Uttarakhand.jpg/1280px-Valley_of_Flowers_Uttarakhand.jpg",
        description:
          "High-altitude hub at 1,890m connecting Nanda Devi biosphere, Valley of Flowers, Har Ki Dun, and Dayara Bugyal. Gateway to some of the most remote and technical expeditions in the Garhwal Himalayas.",
        altitude: 1890,
        bestMonths: ["May", "June", "July", "August", "September", "October"],
        agencyCount: 0,
        startingPrice: 5000,
        isActive: true,
      },
    ];

    let inserted = 0;
    for (const dest of destinations) {
      const exists = await ctx.db
        .query("destinations")
        .withIndex("by_slug", (q) => q.eq("slug", dest.slug))
        .unique();
      if (!exists) {
        await ctx.db.insert("destinations", dest);
        inserted++;
      }
    }
    return { message: "Destinations seeded", inserted, total: destinations.length };
  },
});

// ─── 2. AGENCIES ────────────────────────────────────────────────────────────

export const seedAgencies = mutation({
  args: {},
  handler: async (ctx) => {
    const existingAgencies = await ctx.db.query("agencies").collect();
    if (existingAgencies.length > 0) {
      return { message: "Agencies already seeded", count: existingAgencies.length };
    }

    const allDests = await ctx.db.query("destinations").collect();
    const bySlug: Record<string, string> = Object.fromEntries(
      allDests.map((d) => [d.slug, d._id])
    );

    // ── Region 1: Mussoorie ──────────────────────────────────────────────────
    const mussoorie = bySlug["mussoorie"];
    const mussoorieAgencies = [
      {
        name: "Yeti Outdoors",
        destinationId: mussoorie,
        description:
          "Magical creature ethos reflecting the Himalayas; strictly UIAA/CE certified climbing gear; rigorous Leave No Trace policy; English-speaking, certified alpine guides.",
        address: "Landour Cantt, Mussoorie, Uttarakhand",
        phone: "+91 94100 10001",
        whatsappNumber: "+91 94100 10001",
        yearsInBusiness: 10,
        googleRating: 4.7,
        googleReviewCount: 150,
        isVerified: true,
        specialities: ["Rock Climbing", "Alpine Trekking", "Safety Training", "Leave No Trace"],
        languages: ["Hindi", "English"],
        certifications: ["UIAA Certified", "CE Certified", "First Aid Certified"],
        googleMapsUrl:
          "https://www.google.com/maps/search/?api=1&query=Yeti+Outdoors+Landour+Cantt+Mussoorie",
        isActive: true,
        ...makeTrust(4.7, 150, 10, true),
      },
      {
        name: "Seegreen Lodges",
        destinationId: mussoorie,
        description:
          "Eco-friendly boutique homestay acting as a primary staging ground for the Nag Tibba base camp; pioneers in integrating Shinrin-yoku (Forest Bathing) wellness therapy.",
        address: "Hathipaon, Mussoorie, Uttarakhand",
        phone: "+91 94100 10002",
        whatsappNumber: "+91 94100 10002",
        yearsInBusiness: 12,
        googleRating: 4.6,
        googleReviewCount: 120,
        isVerified: true,
        specialities: ["Eco Trekking", "Forest Bathing", "Nag Tibba Trek", "Wellness Retreats"],
        languages: ["Hindi", "English"],
        certifications: ["Eco-Tourism Certified", "First Aid Certified"],
        googleMapsUrl:
          "https://www.google.com/maps/search/?api=1&query=Seegreen+Lodges+Hathipaon+Mussoorie",
        isActive: true,
        ...makeTrust(4.6, 120, 12, true),
      },
      {
        name: "TrailHikers",
        destinationId: mussoorie,
        description:
          "Customized trekking and specialized eco-friendly nature trails; highly personalized small-group focus with robust 24/7 localized customer support and cultural heritage tours.",
        address: "Mall Road, Mussoorie, Uttarakhand",
        phone: "+91 94100 10003",
        whatsappNumber: "+91 94100 10003",
        yearsInBusiness: 8,
        googleRating: 4.5,
        googleReviewCount: 200,
        isVerified: true,
        specialities: ["Custom Treks", "Eco Trails", "Heritage Tours", "Small Groups"],
        languages: ["Hindi", "English", "Garhwali"],
        certifications: ["Eco-Tourism Certified", "First Aid Certified"],
        googleMapsUrl:
          "https://www.google.com/maps/search/?api=1&query=TrailHikers+Mussoorie",
        isActive: true,
        ...makeTrust(4.5, 200, 8, true),
      },
      {
        name: "Mussoorie ECO Adventure Park",
        destinationId: mussoorie,
        description:
          "The region's largest integrated adventure infrastructure; features the Ferrari Zip Line, 205-foot bungee jumps, and deep-forest off-road mountain wildlife safaris.",
        address: "Hathipaon / Shooting Meadows, Mussoorie, Uttarakhand",
        phone: "+91 94100 10004",
        whatsappNumber: "+91 94100 10004",
        yearsInBusiness: 15,
        googleRating: 4.4,
        googleReviewCount: 500,
        isVerified: true,
        specialities: ["Zip Lining", "Bungee Jumping", "Wildlife Safaris", "Adventure Sports"],
        languages: ["Hindi", "English"],
        certifications: ["Safety Inspection Certified", "First Aid Certified"],
        googleMapsUrl:
          "https://www.google.com/maps/search/?api=1&query=Mussoorie+ECO+Adventure+Park+Hathipaon+Mussoorie",
        isActive: true,
        ...makeTrust(4.4, 500, 15, true),
      },
      {
        name: "Mount Memory Trekking",
        destinationId: mussoorie,
        description:
          "Specialized local trekking organizers focusing heavily on localized, uncrowded trails while maintaining deep community ties and sustainable rural employment.",
        address: "Kyarquli Road Kharadi, Mussoorie, Uttarakhand",
        phone: "+91 94100 10005",
        whatsappNumber: "+91 94100 10005",
        yearsInBusiness: 6,
        googleRating: 4.6,
        googleReviewCount: 80,
        isVerified: false,
        specialities: ["Local Trails", "Uncrowded Routes", "Community Trekking"],
        languages: ["Hindi", "Garhwali", "English"],
        certifications: ["First Aid Certified"],
        googleMapsUrl:
          "https://www.google.com/maps/search/?api=1&query=Mount+Memory+Trekking+Kyarquli+Road+Kharadi+Mussoorie",
        isActive: true,
        ...makeTrust(4.6, 80, 6, false),
      },
      {
        name: "Knock George Camp",
        destinationId: mussoorie,
        description:
          "Niche, highly rated eco-friendly camping operations situated near the historic George Everest peak, isolating guests from commercial zones.",
        address: "Hathi Paon, Mussoorie, Uttarakhand",
        phone: "+91 94100 10006",
        whatsappNumber: "+91 94100 10006",
        yearsInBusiness: 5,
        googleRating: 4.8,
        googleReviewCount: 60,
        isVerified: false,
        specialities: ["Eco Camping", "George Everest Camp", "Nature Retreats"],
        languages: ["Hindi", "English"],
        certifications: ["Eco-Tourism Certified"],
        googleMapsUrl:
          "https://www.google.com/maps/search/?api=1&query=Knock+George+Camp+Hathi+Paon+Mussoorie",
        isActive: true,
        ...makeTrust(4.8, 60, 5, false),
      },
      {
        name: "Oak Valley Camps & Nursery",
        destinationId: mussoorie,
        description:
          "Eco-friendly camping integrated with a plant nursery, emphasizing indigenous flora conservation and environmental education.",
        address: "Charleville, Mussoorie, Uttarakhand",
        phone: "+91 94100 10007",
        whatsappNumber: "+91 94100 10007",
        yearsInBusiness: 7,
        googleRating: 4.5,
        googleReviewCount: 90,
        isVerified: false,
        specialities: ["Eco Camping", "Flora Conservation", "Environmental Education"],
        languages: ["Hindi", "English"],
        certifications: ["Eco-Tourism Certified"],
        googleMapsUrl:
          "https://www.google.com/maps/search/?api=1&query=Oak+Valley+Camps+And+Nursery+Charleville+Mussoorie",
        isActive: true,
        ...makeTrust(4.5, 90, 7, false),
      },
    ];

    // ── Region 2: Rishikesh ──────────────────────────────────────────────────
    const rishikesh = bySlug["rishikesh"];
    const rishikeshAgencies = [
      {
        name: "Snow Leopard Adventures",
        destinationId: rishikesh,
        description:
          "Pioneers in niche aerial training; exclusive river-crossing zip-line over the Ganges requiring ascent.",
        address: "Shivpuri, Rishikesh, Uttarakhand",
        phone: "+91 94100 20001",
        whatsappNumber: "+91 94100 20001",
        yearsInBusiness: 12,
        googleRating: 4.7,
        googleReviewCount: 300,
        isVerified: true,
        specialities: ["Aerial Training", "Zip Lining", "River Crossing", "Adventure Sports"],
        languages: ["Hindi", "English"],
        certifications: ["Grade 4-5 Rafting Certified", "First Aid Certified"],
        googleMapsUrl:
          "https://www.google.com/maps/search/?api=1&query=Snow+Leopard+Adventures+Shivpuri+Rishikesh",
        isActive: true,
        ...makeTrust(4.7, 300, 12, true),
      },
      {
        name: "Thrill Seekers Adventures",
        destinationId: rishikesh,
        description:
          "Extreme safety protocols with safety kayaks, international standards, and premium gear.",
        address: "Singtali Village, Rishikesh, Uttarakhand",
        phone: "+91 94100 20002",
        whatsappNumber: "+91 94100 20002",
        yearsInBusiness: 10,
        googleRating: 4.8,
        googleReviewCount: 250,
        isVerified: true,
        specialities: ["White Water Rafting", "Safety Kayaking", "Extreme Adventures"],
        languages: ["Hindi", "English"],
        certifications: ["International Safety Certified", "Grade 4-5 Rafting Certified"],
        googleMapsUrl:
          "https://www.google.com/maps/search/?api=1&query=Thrill+Seekers+Adventures+Singtali+Village+Rishikesh",
        isActive: true,
        ...makeTrust(4.8, 250, 10, true),
      },
      {
        name: "Adventure Rishikesh India",
        destinationId: rishikesh,
        description:
          "Hybrid packages combining rafting with Hatha and Ashtanga yoga retreats.",
        address: "Tapovan, Rishikesh, Uttarakhand",
        phone: "+91 94100 20003",
        whatsappNumber: "+91 94100 20003",
        yearsInBusiness: 8,
        googleRating: 4.5,
        googleReviewCount: 200,
        isVerified: true,
        specialities: ["Rafting", "Hatha Yoga", "Ashtanga Yoga", "Hybrid Packages"],
        languages: ["Hindi", "English"],
        certifications: ["Yoga Alliance Certified", "Grade 3-4 Rafting Certified"],
        googleMapsUrl:
          "https://www.google.com/maps/search/?api=1&query=Adventure+Rishikesh+India+Tapovan+Rishikesh",
        isActive: true,
        ...makeTrust(4.5, 200, 8, true),
      },
      {
        name: "White World Expeditions",
        destinationId: rishikesh,
        description:
          "Premium luxury tours avoiding mass commercial rafting crowds.",
        address: "Rishikesh, Uttarakhand",
        phone: "+91 94100 20004",
        whatsappNumber: "+91 94100 20004",
        yearsInBusiness: 15,
        googleRating: 4.6,
        googleReviewCount: 180,
        isVerified: true,
        specialities: ["Luxury Rafting", "Premium Tours", "Private Groups"],
        languages: ["Hindi", "English"],
        certifications: ["Grade 4-5 Rafting Certified", "First Aid Certified"],
        googleMapsUrl:
          "https://www.google.com/maps/search/?api=1&query=White+World+Expeditions+Rishikesh",
        isActive: true,
        ...makeTrust(4.6, 180, 15, true),
      },
      {
        name: "Rishikesh Rafting Adventure",
        destinationId: rishikesh,
        description:
          "70km long-haul river expeditions from Devprayag with multi-day camping.",
        address: "Gaura Devi Chowk, Rishikesh, Uttarakhand",
        phone: "+91 94100 20005",
        whatsappNumber: "+91 94100 20005",
        yearsInBusiness: 7,
        googleRating: 4.4,
        googleReviewCount: 150,
        isVerified: false,
        specialities: ["Long-Haul Rafting", "Multi-Day Camping", "Devprayag Expeditions"],
        languages: ["Hindi", "English"],
        certifications: ["Grade 3-4 Rafting Certified"],
        googleMapsUrl:
          "https://www.google.com/maps/search/?api=1&query=Rishikesh+Rafting+Adventure+Gaura+Devi+Chowk+Rishikesh",
        isActive: true,
        ...makeTrust(4.4, 150, 7, false),
      },
      {
        name: "Himalaya Expedition",
        destinationId: rishikesh,
        description:
          "Small-group, thrill-focused rafting led by experienced local navigators.",
        address: "Rishikesh, Uttarakhand",
        phone: "+91 94100 20006",
        whatsappNumber: "+91 94100 20006",
        yearsInBusiness: 9,
        googleRating: 4.5,
        googleReviewCount: 120,
        isVerified: false,
        specialities: ["Small-Group Rafting", "River Navigation", "Adventure Tours"],
        languages: ["Hindi", "English", "Garhwali"],
        certifications: ["Grade 3-4 Rafting Certified", "First Aid Certified"],
        googleMapsUrl:
          "https://www.google.com/maps/search/?api=1&query=Himalaya+Expedition+Rishikesh",
        isActive: true,
        ...makeTrust(4.5, 120, 9, false),
      },
      {
        name: "Himalayan Gipsy",
        destinationId: rishikesh,
        description:
          "Eco-conscious riverside camping away from crowded tourist zones.",
        address: "Taliyal Gaon, Rishikesh, Uttarakhand",
        phone: "+91 94100 20007",
        whatsappNumber: "+91 94100 20007",
        yearsInBusiness: 6,
        googleRating: 4.7,
        googleReviewCount: 80,
        isVerified: false,
        specialities: ["Eco Camping", "Riverside Camping", "Sustainable Tourism"],
        languages: ["Hindi", "English"],
        certifications: ["Eco-Tourism Certified"],
        googleMapsUrl:
          "https://www.google.com/maps/search/?api=1&query=Himalayan+Gipsy+Taliyal+Gaon+Rishikesh",
        isActive: true,
        ...makeTrust(4.7, 80, 6, false),
      },
    ];

    // ── Region 3: Chopta ─────────────────────────────────────────────────────
    const chopta = bySlug["chopta"];
    const choptaAgencies = [
      {
        name: "Lake Haven Resort",
        destinationId: chopta,
        description:
          "Luxury basecamp for Deoria Tal; high-altitude acclimatization rooms and Garhwali cuisine.",
        address: "Sari Village, Chopta, Uttarakhand",
        phone: "+91 94100 30001",
        whatsappNumber: "+91 94100 30001",
        yearsInBusiness: 8,
        googleRating: 4.7,
        googleReviewCount: 200,
        isVerified: true,
        specialities: ["Deoria Tal Trek", "Altitude Acclimatization", "Luxury Base Camp"],
        languages: ["Hindi", "English", "Garhwali"],
        certifications: ["Eco-Tourism Certified", "First Aid Certified"],
        googleMapsUrl:
          "https://www.google.com/maps/search/?api=1&query=Lake+Haven+Resort+Sari+Village+Chopta",
        isActive: true,
        ...makeTrust(4.7, 200, 8, true),
      },
      {
        name: "Indian Treks",
        destinationId: chopta,
        description:
          "Premium Swiss camps; NIM-certified guides with 12+ years experience.",
        address: "Sari Village, Chopta, Uttarakhand",
        phone: "+91 94100 30002",
        whatsappNumber: "+91 94100 30002",
        yearsInBusiness: 12,
        googleRating: 4.8,
        googleReviewCount: 180,
        isVerified: true,
        specialities: ["Tungnath Trek", "NIM-Certified Guides", "Premium Camping"],
        languages: ["Hindi", "English"],
        certifications: ["NIM Certified", "First Aid Certified"],
        googleMapsUrl:
          "https://www.google.com/maps/search/?api=1&query=Indian+Treks+Sari+Village+Chopta",
        isActive: true,
        ...makeTrust(4.8, 180, 12, true),
      },
      {
        name: "Anala Outdoors",
        destinationId: chopta,
        description:
          "30+ years experience; female-led, satellite updates, strict safety protocols.",
        address: "Chopta, Uttarakhand",
        phone: "+91 94100 30003",
        whatsappNumber: "+91 94100 30003",
        yearsInBusiness: 30,
        googleRating: 4.7,
        googleReviewCount: 150,
        isVerified: true,
        specialities: ["High-Altitude Trekking", "Female-Led Expeditions", "Satellite Navigation"],
        languages: ["Hindi", "English"],
        certifications: ["NIM Certified", "Wilderness First Responder", "Satellite Safety Certified"],
        googleMapsUrl:
          "https://www.google.com/maps/search/?api=1&query=Anala+Outdoors+Chopta",
        isActive: true,
        ...makeTrust(4.7, 150, 30, true),
      },
      {
        name: "Trek Pole",
        destinationId: chopta,
        description:
          "Affordable packages with local Garhwali guides for cultural immersion.",
        address: "Dehradun / Chopta, Uttarakhand",
        phone: "+91 94100 30004",
        whatsappNumber: "+91 94100 30004",
        yearsInBusiness: 7,
        googleRating: 4.5,
        googleReviewCount: 120,
        isVerified: false,
        specialities: ["Budget Trekking", "Cultural Immersion", "Garhwali Guided Treks"],
        languages: ["Hindi", "Garhwali", "English"],
        certifications: ["First Aid Certified"],
        googleMapsUrl:
          "https://www.google.com/maps/search/?api=1&query=Trek+Pole+Chopta",
        isActive: true,
        ...makeTrust(4.5, 120, 7, false),
      },
      {
        name: "Shiva Adventures",
        destinationId: chopta,
        description:
          "Specialized in Chopta–Tungnath–Chandrashila treks with beginner-friendly approach.",
        address: "Chopta, Uttarakhand",
        phone: "+91 94100 30005",
        whatsappNumber: "+91 94100 30005",
        yearsInBusiness: 8,
        googleRating: 4.6,
        googleReviewCount: 100,
        isVerified: false,
        specialities: ["Tungnath Trek", "Chandrashila Trek", "Beginner Trekking"],
        languages: ["Hindi", "English"],
        certifications: ["First Aid Certified"],
        googleMapsUrl:
          "https://www.google.com/maps/search/?api=1&query=Shiva+Adventures+Chopta",
        isActive: true,
        ...makeTrust(4.6, 100, 8, false),
      },
      {
        name: "Devbhoomi Trek",
        destinationId: chopta,
        description:
          "Experts in permits, porter management, and high-altitude logistics.",
        address: "Sari Village, Chopta, Uttarakhand",
        phone: "+91 94100 30006",
        whatsappNumber: "+91 94100 30006",
        yearsInBusiness: 6,
        googleRating: 4.5,
        googleReviewCount: 80,
        isVerified: false,
        specialities: ["Permit Management", "Porter Services", "High-Altitude Logistics"],
        languages: ["Hindi", "Garhwali", "English"],
        certifications: ["First Aid Certified"],
        googleMapsUrl:
          "https://www.google.com/maps/search/?api=1&query=Devbhoomi+Trek+Sari+Village+Chopta",
        isActive: true,
        ...makeTrust(4.5, 80, 6, false),
      },
      {
        name: "Travelophila",
        destinationId: chopta,
        description:
          "Combines Char Dham pilgrimage with beginner-friendly trekking.",
        address: "Chopta, Uttarakhand",
        phone: "+91 94100 30007",
        whatsappNumber: "+91 94100 30007",
        yearsInBusiness: 5,
        googleRating: 4.4,
        googleReviewCount: 60,
        isVerified: false,
        specialities: ["Char Dham Pilgrimage", "Beginner Trekking", "Religious Tours"],
        languages: ["Hindi", "English"],
        certifications: ["First Aid Certified"],
        googleMapsUrl:
          "https://www.google.com/maps/search/?api=1&query=Travelophila+Chopta",
        isActive: true,
        ...makeTrust(4.4, 60, 5, false),
      },
    ];

    // ── Region 4: Kedarkantha ────────────────────────────────────────────────
    const kedarkantha = bySlug["kedarkantha"];
    const kedarkanthaAgencies = [
      {
        name: "Kedarkantha Official (JTH Unit)",
        destinationId: kedarkantha,
        description:
          "Local staff, strong crisis management, Leave No Trace policy.",
        address: "Sankri, Uttarkashi, Uttarakhand",
        phone: "+91 94100 40001",
        whatsappNumber: "+91 94100 40001",
        yearsInBusiness: 10,
        googleRating: 4.7,
        googleReviewCount: 250,
        isVerified: true,
        specialities: ["Kedarkantha Summit", "Crisis Management", "Leave No Trace"],
        languages: ["Hindi", "English"],
        certifications: ["NIM Certified", "Wilderness First Responder"],
        googleMapsUrl:
          "https://www.google.com/maps/search/?api=1&query=Kedarkantha+Official+Sankri",
        isActive: true,
        ...makeTrust(4.7, 250, 10, true),
      },
      {
        name: "Pahadi Odyssey",
        destinationId: kedarkantha,
        description:
          "Real-time snow reports, flexible departures, cultural experiences.",
        address: "Purola / Sankri, Uttarkashi, Uttarakhand",
        phone: "+91 94100 40002",
        whatsappNumber: "+91 94100 40002",
        yearsInBusiness: 8,
        googleRating: 4.6,
        googleReviewCount: 180,
        isVerified: false,
        specialities: ["Winter Trekking", "Snow Reports", "Flexible Departures"],
        languages: ["Hindi", "English", "Garhwali"],
        certifications: ["First Aid Certified"],
        googleMapsUrl:
          "https://www.google.com/maps/search/?api=1&query=Pahadi+Odyssey+Purola+Sankri",
        isActive: true,
        ...makeTrust(4.6, 180, 8, false),
      },
      {
        name: "Himalayan Hikers",
        destinationId: kedarkantha,
        description:
          "34+ years legacy; school camps and sustainability programs.",
        address: "Sankri, Uttarkashi, Uttarakhand",
        phone: "+91 94100 40003",
        whatsappNumber: "+91 94100 40003",
        yearsInBusiness: 34,
        googleRating: 4.8,
        googleReviewCount: 300,
        isVerified: true,
        specialities: ["Winter Expeditions", "School Camps", "Sustainability Programs"],
        languages: ["Hindi", "English"],
        certifications: ["NIM Certified", "UIAA Certified", "First Aid Certified"],
        googleMapsUrl:
          "https://www.google.com/maps/search/?api=1&query=Himalayan+Hikers+Sankri",
        isActive: true,
        ...makeTrust(4.8, 300, 34, true),
      },
      {
        name: "The Searching Souls",
        destinationId: kedarkantha,
        description:
          "Experts in extreme winter treks and frozen lake expeditions.",
        address: "Sankri, Uttarkashi, Uttarakhand",
        phone: "+91 94100 40004",
        whatsappNumber: "+91 94100 40004",
        yearsInBusiness: 7,
        googleRating: 4.7,
        googleReviewCount: 150,
        isVerified: false,
        specialities: ["Extreme Winter Treks", "Frozen Lake Expeditions", "Backcountry Trekking"],
        languages: ["Hindi", "English"],
        certifications: ["Wilderness First Responder", "First Aid Certified"],
        googleMapsUrl:
          "https://www.google.com/maps/search/?api=1&query=The+Searching+Souls+Sankri",
        isActive: true,
        ...makeTrust(4.7, 150, 7, false),
      },
      {
        name: "Hillway Treks",
        destinationId: kedarkantha,
        description:
          "Local, uncommercialized treks into Govind Wildlife Sanctuary.",
        address: "Saur Village, Sankri, Uttarakhand",
        phone: "+91 94100 40005",
        whatsappNumber: "+91 94100 40005",
        yearsInBusiness: 5,
        googleRating: 4.5,
        googleReviewCount: 80,
        isVerified: false,
        specialities: ["Wildlife Sanctuary Treks", "Local Routes", "Govind Wildlife Sanctuary"],
        languages: ["Hindi", "Garhwali", "English"],
        certifications: ["First Aid Certified"],
        googleMapsUrl:
          "https://www.google.com/maps/search/?api=1&query=Hillway+Treks+Saur+Village+Sankri",
        isActive: true,
        ...makeTrust(4.5, 80, 5, false),
      },
      {
        name: "Tons Trails Pvt Ltd",
        destinationId: kedarkantha,
        description:
          "Routes through Tons valley with ecology-driven operations.",
        address: "Kotgaon, Sankri, Uttarakhand",
        phone: "+91 94100 40006",
        whatsappNumber: "+91 94100 40006",
        yearsInBusiness: 9,
        googleRating: 4.6,
        googleReviewCount: 120,
        isVerified: true,
        specialities: ["Tons Valley Treks", "Ecology-Driven Expeditions", "Remote Routes"],
        languages: ["Hindi", "English"],
        certifications: ["Eco-Tourism Certified", "First Aid Certified"],
        googleMapsUrl:
          "https://www.google.com/maps/search/?api=1&query=Tons+Trails+Pvt+Ltd+Kotgaon+Sankri",
        isActive: true,
        ...makeTrust(4.6, 120, 9, true),
      },
      {
        name: "Kailashrath Treks",
        destinationId: kedarkantha,
        description:
          "Transport specialists with seamless Dehradun–Sankri connectivity.",
        address: "Sankri, Uttarkashi, Uttarakhand",
        phone: "+91 94100 40007",
        whatsappNumber: "+91 94100 40007",
        yearsInBusiness: 6,
        googleRating: 4.4,
        googleReviewCount: 60,
        isVerified: false,
        specialities: ["Transport Services", "Dehradun Connectivity", "Trek Logistics"],
        languages: ["Hindi", "English"],
        certifications: ["First Aid Certified"],
        googleMapsUrl:
          "https://www.google.com/maps/search/?api=1&query=Kailashrath+Treks+Sankri",
        isActive: true,
        ...makeTrust(4.4, 60, 6, false),
      },
    ];

    // ── Region 5: Joshimath / High-Altitude Hubs ─────────────────────────────
    const joshimath = bySlug["joshimath"];
    const joshimathAgencies = [
      {
        name: "Mountain Shepherds Initiative",
        destinationId: joshimath,
        description:
          "Community-owned by Bhotiya tribe; protects Nanda Devi biosphere.",
        address: "Lata Village, Joshimath, Uttarakhand",
        phone: "+91 94100 50001",
        whatsappNumber: "+91 94100 50001",
        yearsInBusiness: 15,
        googleRating: 4.9,
        googleReviewCount: 200,
        isVerified: true,
        specialities: ["Community Based Tourism", "Nanda Devi Biosphere", "Bhotiya Culture", "Remote Expeditions"],
        languages: ["Hindi", "English", "Kumaoni"],
        certifications: ["NIM Certified", "Eco-Tourism Certified", "Wilderness First Responder"],
        googleMapsUrl:
          "https://www.google.com/maps/search/?api=1&query=Mountain+Shepherds+Initiative+Lata+Village+Joshimath",
        isActive: true,
        ...makeTrust(4.9, 200, 15, true),
      },
      {
        name: "Blue Poppy Holidays",
        destinationId: joshimath,
        description:
          "Valley of Flowers specialists with senior-friendly logistics.",
        address: "Ghangaria / Auli, Joshimath, Uttarakhand",
        phone: "+91 94100 50002",
        whatsappNumber: "+91 94100 50002",
        yearsInBusiness: 10,
        googleRating: 4.6,
        googleReviewCount: 150,
        isVerified: true,
        specialities: ["Valley of Flowers", "Auli Skiing", "Senior-Friendly Treks"],
        languages: ["Hindi", "English"],
        certifications: ["First Aid Certified"],
        googleMapsUrl:
          "https://www.google.com/maps/search/?api=1&query=Blue+Poppy+Holidays+Ghangaria+Joshimath",
        isActive: true,
        ...makeTrust(4.6, 150, 10, true),
      },
      {
        name: "Valley Of Flowers Trekking Tour Operators",
        destinationId: joshimath,
        description:
          "Trekking + cycling combinations in Chamoli.",
        address: "Pandukeshwar, Joshimath, Uttarakhand",
        phone: "+91 94100 50003",
        whatsappNumber: "+91 94100 50003",
        yearsInBusiness: 8,
        googleRating: 4.5,
        googleReviewCount: 120,
        isVerified: false,
        specialities: ["Valley of Flowers", "Cycling Tours", "Chamoli Treks"],
        languages: ["Hindi", "English"],
        certifications: ["First Aid Certified"],
        googleMapsUrl:
          "https://www.google.com/maps/search/?api=1&query=Valley+Of+Flowers+Trekking+Tour+Operators+Pandukeshwar+Joshimath",
        isActive: true,
        ...makeTrust(4.5, 120, 8, false),
      },
      {
        name: "Trektonic Adventures",
        destinationId: joshimath,
        description:
          "Experts in Har Ki Dun & Dayara Bugyal logistics.",
        address: "Dehradun / Uttarkashi, Uttarakhand",
        phone: "+91 94100 50004",
        whatsappNumber: "+91 94100 50004",
        yearsInBusiness: 7,
        googleRating: 4.7,
        googleReviewCount: 100,
        isVerified: false,
        specialities: ["Har Ki Dun", "Dayara Bugyal", "Expedition Logistics"],
        languages: ["Hindi", "English"],
        certifications: ["NIM Certified", "First Aid Certified"],
        googleMapsUrl:
          "https://www.google.com/maps/search/?api=1&query=Trektonic+Adventures+Uttarkashi",
        isActive: true,
        ...makeTrust(4.7, 100, 7, false),
      },
      {
        name: "Adventure Heights",
        destinationId: joshimath,
        description:
          "Technical expeditions like KedarTal & Bagini Glacier.",
        address: "Uttarkashi, Uttarakhand",
        phone: "+91 94100 50005",
        whatsappNumber: "+91 94100 50005",
        yearsInBusiness: 12,
        googleRating: 4.6,
        googleReviewCount: 150,
        isVerified: true,
        specialities: ["Technical Climbing", "Kedar Tal Trek", "Bagini Glacier", "Expert Expeditions"],
        languages: ["Hindi", "English"],
        certifications: ["UIAA Certified", "NIM Certified", "Wilderness First Responder"],
        googleMapsUrl:
          "https://www.google.com/maps/search/?api=1&query=Adventure+Heights+Uttarkashi",
        isActive: true,
        ...makeTrust(4.6, 150, 12, true),
      },
      {
        name: "Trekking Team Group",
        destinationId: joshimath,
        description:
          "Multi-week glacier expeditions with strong logistics.",
        address: "Uttarkashi, Uttarakhand",
        phone: "+91 94100 50006",
        whatsappNumber: "+91 94100 50006",
        yearsInBusiness: 10,
        googleRating: 4.5,
        googleReviewCount: 120,
        isVerified: false,
        specialities: ["Multi-Week Glacier Expeditions", "High-Altitude Logistics", "Remote Trekking"],
        languages: ["Hindi", "English"],
        certifications: ["NIM Certified", "First Aid Certified"],
        googleMapsUrl:
          "https://www.google.com/maps/search/?api=1&query=Trekking+Team+Group+Uttarkashi",
        isActive: true,
        ...makeTrust(4.5, 120, 10, false),
      },
      {
        name: "eUttaranchal",
        destinationId: joshimath,
        description:
          "Customized groups with premium homestays and meals.",
        address: "Joshimath, Uttarakhand",
        phone: "+91 94100 50007",
        whatsappNumber: "+91 94100 50007",
        yearsInBusiness: 8,
        googleRating: 4.4,
        googleReviewCount: 80,
        isVerified: false,
        specialities: ["Customized Group Tours", "Premium Homestays", "Cultural Experiences"],
        languages: ["Hindi", "English"],
        certifications: ["First Aid Certified"],
        googleMapsUrl:
          "https://www.google.com/maps/search/?api=1&query=eUttaranchal+Joshimath",
        isActive: true,
        ...makeTrust(4.4, 80, 8, false),
      },
      {
        name: "Dream Go Himalayas",
        destinationId: joshimath,
        description:
          "Structured Valley of Flowers routes with smooth logistics.",
        address: "Haridwar, Uttarakhand",
        phone: "+91 94100 50008",
        whatsappNumber: "+91 94100 50008",
        yearsInBusiness: 6,
        googleRating: 4.5,
        googleReviewCount: 100,
        isVerified: false,
        specialities: ["Valley of Flowers", "Structured Routes", "Haridwar Base Tours"],
        languages: ["Hindi", "English"],
        certifications: ["First Aid Certified"],
        googleMapsUrl:
          "https://www.google.com/maps/search/?api=1&query=Dream+Go+Himalayas+Haridwar",
        isActive: true,
        ...makeTrust(4.5, 100, 6, false),
      },
    ];

    // ── Insert all agencies ──────────────────────────────────────────────────
    const allAgencies = [
      ...mussoorieAgencies,
      ...rishikeshAgencies,
      ...choptaAgencies,
      ...kedarkanthaAgencies,
      ...joshimathAgencies,
    ];

    const ids = [];
    for (const agency of allAgencies) {
      ids.push(await ctx.db.insert("agencies", agency));
    }

    // Update agencyCount on each destination
    for (const dest of allDests) {
      const count = await ctx.db
        .query("agencies")
        .withIndex("by_destination", (q) => q.eq("destinationId", dest._id))
        .collect();
      await ctx.db.patch(dest._id, { agencyCount: count.length });
    }

    return { message: "Agencies seeded successfully", count: ids.length };
  },
});
