// @ts-nocheck — types generated by `npx convex dev`
import { mutation } from "./_generated/server";

export const seedDestinations = mutation({
  args: {},
  handler: async (ctx) => {
    // Avoid duplicate seeding
    const existing = await ctx.db.query("destinations").collect();
    if (existing.length > 0) {
      return { message: "Already seeded", count: existing.length };
    }

    const destinations = [
      {
        name: "Mussoorie",
        slug: "mussoorie",
        region: "Uttarakhand",
        heroImageUrl:
          "https://upload.wikimedia.org/wikipedia/commons/thumb/5/5c/Mussoorie_Queen_of_Hills.jpg/1280px-Mussoorie_Queen_of_Hills.jpg",
        description:
          "Known as the Queen of Hills, Mussoorie sits at 2,005m in the Garhwal Himalayan range. A favourite year-round hill station with scenic trails, waterfalls and colonial charm.",
        altitude: 2005,
        bestMonths: ["March", "April", "May", "September", "October", "November"],
        agencyCount: 0,
        startingPrice: 2500,
        isActive: true,
      },
      {
        name: "Rishikesh",
        slug: "rishikesh",
        region: "Uttarakhand",
        heroImageUrl:
          "https://upload.wikimedia.org/wikipedia/commons/thumb/3/3e/Laxman_Jhula_Rishikesh.jpg/1280px-Laxman_Jhula_Rishikesh.jpg",
        description:
          "The adventure capital of India on the banks of the Ganges. Gateway to the Garhwal Himalayas — white-water rafting, yoga, camping and multi-day treks all start here.",
        altitude: 372,
        bestMonths: [
          "February",
          "March",
          "April",
          "May",
          "September",
          "October",
          "November",
        ],
        agencyCount: 0,
        startingPrice: 1800,
        isActive: true,
      },
      {
        name: "Chopta",
        slug: "chopta",
        region: "Uttarakhand",
        heroImageUrl:
          "https://upload.wikimedia.org/wikipedia/commons/thumb/6/6e/Tungnath_Temple.jpg/1280px-Tungnath_Temple.jpg",
        description:
          "Called the Mini Switzerland of India. At 2,680m, Chopta is the base for the Tungnath–Chandrashila trek — one of the most scenic winter treks in the Himalayas.",
        altitude: 2680,
        bestMonths: [
          "March",
          "April",
          "May",
          "October",
          "November",
          "December",
          "January",
        ],
        agencyCount: 0,
        startingPrice: 3200,
        isActive: true,
      },
      {
        name: "Kedarkantha",
        slug: "kedarkantha",
        region: "Uttarakhand",
        heroImageUrl:
          "https://upload.wikimedia.org/wikipedia/commons/thumb/2/2d/Kedarkantha_peak.jpg/1280px-Kedarkantha_peak.jpg",
        description:
          "A perfect winter summit trek at 3,810m. Kedarkantha offers meadows blanketed in snow, dense pine forests and 360° panoramic views of peaks including Bandarpoonch and Swargarohini.",
        altitude: 3810,
        bestMonths: ["December", "January", "February", "March", "April"],
        agencyCount: 0,
        startingPrice: 4500,
        isActive: true,
      },
    ];

    const ids = [];
    for (const dest of destinations) {
      const id = await ctx.db.insert("destinations", dest);
      ids.push(id);
    }

    return { message: "Seeded successfully", count: ids.length, ids };
  },
});
