// @ts-nocheck — types generated by `npx convex dev`
import { query } from "./_generated/server";
import { v } from "convex/values";

export const listByAgency = query({
  args: { agencyId: v.id("agencies") },
  handler: async (ctx, args) => {
    return await ctx.db
      .query("treks")
      .withIndex("by_agency", (q) => q.eq("agencyId", args.agencyId))
      .filter((q) => q.eq(q.field("isActive"), true))
      .collect();
  },
});

export const getById = query({
  args: { id: v.id("treks") },
  handler: async (ctx, args) => {
    return await ctx.db.get(args.id);
  },
});
